/******************* Library for basic calculation routines ********************

   Author(s):   Manuel Jander

   Description: FDK tools versioning support

*******************************************************************************/

#ifndef FDK_CORE_H
#define FDK_CORE_H

#include "FDK_audio.h"

#ifdef __cplusplus
extern "C" {
#endif

int FDK_toolsGetLibInfo(LIB_INFO *info);

#ifdef __cplusplus
}
#endif

#endif
