/******************* MPEG transport format encoder library *********************

   Author(s):

   Description:

*******************************************************************************/

#if !defined(TP_VERSION_H)
#define TP_VERSION_H

#define TP_LIB_VL0 3
#define TP_LIB_VL1 0
#define TP_LIB_VL2 0
#define TP_LIB_TITLE "MPEG Transport"
#define TP_LIB_BUILD_DATE ""
#define TP_LIB_BUILD_TIME ""
#endif /* !defined(TP_VERSION_H) */
