/**************************** PCM utility library ******************************

   Author(s):

   Description:

*******************************************************************************/

#if !defined(VERSION_H)
#define VERSION_H

#define PCMUTIL_LIB_VL0 3
#define PCMUTIL_LIB_VL1 1
#define PCMUTIL_LIB_VL2 0
#define PCMUTIL_LIB_TITLE "PCM Utility Lib"
#define PCMUTIL_LIB_BUILD_DATE ""
#define PCMUTIL_LIB_BUILD_TIME ""

#endif /* !defined(VERSION_H) */
